# Only build master branch that contains David's CV
branches:
  only:
  - master
  - fix-broken-build

os: linux
dist: xenial
language: shell

services:
- docker

before_install:
- mkdir output
- docker pull thomasweise/texlive

# Build doc twice to get \LastPage labels defined
script:
- docker run -v ${PWD}:/doc/ -ti thomasweise/texlive make cv resume
- docker run -v ${PWD}:/doc/ -ti thomasweise/texlive make cv resume
- mv *.pdf output/

deploy:
  provider: s3
  bucket: davidcharbonnier-cv
  region: ca-central-1
  local_dir: output
  acl: public_read
  edge: true # opt in to dpl v2
